---
imagemagick_pkg:
  version: 7.0.10-59
  pkgs:
    - imagemagick-distribution-libs-linux
    - imagemagick-distribution-linux

libreoffice: 7.1.3.2
pdf_renderer: 1.1
imagemagick_home: "/usr/lib64/ImageMagick-{{ imagemagick_pkg.version.split('-',0) }}"
